"use client";

// About You tab — surfaces the `user-analyst` agent's output as a candid,
// evidence-cited analysis of the user. The tab has three states:
//
//   1. First-run   (no analysis file yet) → empty-state + "Generate" button.
//   2. Idle        (analysis exists, no regen in flight) → rendered markdown
//                   + "Updated Xm ago" + "Regenerate" (inline confirm chip).
//   3. Regenerating (a user-analyst runId is being polled) → loading state,
//                   auto-refetches the analysis when the run finishes.
//
// The inline confirm-chip idiom mirrors the per-instance delete pattern in
// modules/office/components/agent-details (Ticket 2). The markdown renderer
// is ProseView from components/ui/prose-view — the same one used elsewhere.

import { useEffect, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Card } from "@/components/ui/card";
import { CardHeader } from "@/components/ui/card-header";
import { Button } from "@/components/ui/button";
import { Icon } from "@/components/ui/icon";
import { Skeleton } from "@/components/ui/skeleton";
import { ProseView } from "@/components/ui/prose-view";
import { queryKeys } from "@agent-office/shared/hooks/query-keys";
import { formatRelative } from "@/modules/runs/utils/format-run-meta";
import { useRun } from "@/modules/runs/hooks/use-runs";
import { POLL } from "@/lib/polling";
import { useUserAnalysis, useRegenerateUserAnalysis } from "../../hooks/use-user-analysis";

const REGENERATE_WARNING =
  "Regenerate will spend ~$0.30–1.00 in Opus tokens. Analysis may take 2–5 minutes.";

export function AboutYouTab() {
  const analysisQ = useUserAnalysis();
  const regenMut = useRegenerateUserAnalysis();
  const qc = useQueryClient();

  const [confirming, setConfirming] = useState(false);
  const [activeRunId, setActiveRunId] = useState<string | null>(null);

  const runQ = useRun(activeRunId);
  const runStatus = runQ.data?.status;

  // Poll the active run every 5s while it's still running, then stop.
  useEffect(() => {
    if (!activeRunId) return;
    const stillRunning = runStatus === "running" || runStatus === undefined;
    if (!stillRunning) return;
    const interval = window.setInterval(() => {
      qc.invalidateQueries({ queryKey: queryKeys.runs.detail(activeRunId) });
    }, POLL.RUNS);
    return () => window.clearInterval(interval);
  }, [activeRunId, runStatus, qc]);

  // Once the run finishes, refetch the analysis + clear the active runId so
  // the next click starts a fresh regen.
  useEffect(() => {
    if (!activeRunId) return;
    if (runStatus === "done" || runStatus === "error") {
      qc.invalidateQueries({ queryKey: queryKeys.settings.userAnalysis() });
      setActiveRunId(null);
    }
  }, [activeRunId, runStatus, qc]);

  const startRegenerate = async () => {
    setConfirming(false);
    const res = await regenMut.mutateAsync();
    setActiveRunId(res.runId);
  };

  const isRegenerating = activeRunId !== null || regenMut.isPending;
  const runFailed = runStatus === "error";

  if (analysisQ.isLoading) {
    return (
      <Card>
        <div className="p-4">
          <Skeleton width="100%" height={220} />
        </div>
      </Card>
    );
  }

  const analysis = analysisQ.data;
  const hasAnalysis = analysis?.markdown && analysis.markdown.trim().length > 0;

  return (
    <Card>
      <CardHeader
        title="About you"
        sub="A candid, evidence-cited analysis generated by the user-analyst agent from your local Agent Office data, projects, and prior recon reports."
      />

      {!hasAnalysis ? (
        <EmptyState
          onGenerate={startRegenerate}
          isRegenerating={isRegenerating}
          runFailed={runFailed}
        />
      ) : (
        <AnalysisView
          markdown={analysis.markdown!}
          updatedAt={analysis.updatedAt}
          wordCount={analysis.wordCount}
          confirming={confirming}
          isRegenerating={isRegenerating}
          runFailed={runFailed}
          onConfirmStart={() => setConfirming(true)}
          onConfirmCancel={() => setConfirming(false)}
          onConfirmProceed={startRegenerate}
        />
      )}
    </Card>
  );
}

// ── Sub-components ────────────────────────────────────────────────────────

function EmptyState({
  onGenerate,
  isRegenerating,
  runFailed,
}: {
  onGenerate: () => void;
  isRegenerating: boolean;
  runFailed: boolean;
}) {
  return (
    <div className="p-6 flex flex-col items-center gap-3 text-center">
      <div className="w-12 h-12 rounded-full bg-ao-bg-3 border border-ao-line-1 flex items-center justify-center text-ao-fg-2">
        <Icon name="sparkle" size={20} />
      </div>
      <div className="text-[14px] font-semibold text-ao-fg-0">
        No analysis yet
      </div>
      <p className="m-0 text-[13px] text-ao-fg-2 max-w-[440px] leading-[1.55]">
        Generate a candid analysis of your workflow, portfolio drift, and
        recurring patterns. Runs against your local SQLite, projects, agent
        memories, and prior recon reports.
      </p>
      <p className="m-0 text-[11.5px] text-ao-fg-3 font-mono">
        {REGENERATE_WARNING}
      </p>
      {runFailed ? <ErrorPill /> : null}
      <Button variant="primary" onClick={onGenerate} disabled={isRegenerating}>
        {isRegenerating ? (
          <>
            <Spinner /> Generating…
          </>
        ) : (
          <>
            <Icon name="sparkle" size={13} /> Generate your analysis
          </>
        )}
      </Button>
    </div>
  );
}

function AnalysisView({
  markdown,
  updatedAt,
  wordCount,
  confirming,
  isRegenerating,
  runFailed,
  onConfirmStart,
  onConfirmCancel,
  onConfirmProceed,
}: {
  markdown: string;
  updatedAt: string | null;
  wordCount: number | null;
  confirming: boolean;
  isRegenerating: boolean;
  runFailed: boolean;
  onConfirmStart: () => void;
  onConfirmCancel: () => void;
  onConfirmProceed: () => void;
}) {
  const updatedLabel = updatedAt
    ? `Updated ${formatRelative(new Date(updatedAt).getTime())}`
    : "Updated —";
  const wordLabel = wordCount ? `${wordCount.toLocaleString()} words` : null;

  return (
    <>
      <div className="flex items-center gap-3 px-4 py-3 border-b border-ao-line-1 bg-ao-bg-2">
        <span className="text-[11.5px] font-mono text-ao-fg-2">
          {updatedLabel}
          {wordLabel ? <span className="text-ao-fg-3"> · {wordLabel}</span> : null}
        </span>
        {runFailed ? <ErrorPill /> : null}
        <div className="ml-auto flex items-center gap-2">
          {isRegenerating ? (
            <span className="inline-flex items-center gap-2 text-[12px] font-mono text-ao-fg-2">
              <Spinner /> Regenerating…
            </span>
          ) : confirming ? (
            <ConfirmChip
              message={REGENERATE_WARNING}
              onCancel={onConfirmCancel}
              onProceed={onConfirmProceed}
            />
          ) : (
            <Button onClick={onConfirmStart}>
              <Icon name="refresh" size={12} /> Regenerate
            </Button>
          )}
        </div>
      </div>
      <div className="p-4 ao-prose">
        <ProseView body={markdown} />
      </div>
    </>
  );
}

function ConfirmChip({
  message,
  onCancel,
  onProceed,
}: {
  message: string;
  onCancel: () => void;
  onProceed: () => void;
}) {
  return (
    <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-md bg-ao-bg-3 border border-ao-line-2">
      <span className="text-[11.5px] font-mono text-ao-fg-1 max-w-[360px]">
        {message}
      </span>
      <button
        type="button"
        onClick={onCancel}
        className="px-2 py-0.5 rounded text-[11.5px] font-mono text-ao-fg-2 hover:text-ao-fg-0 hover:bg-ao-line-1/40 focus:outline-none focus-visible:ring-2 focus-visible:ring-ao-accent-line"
      >
        Cancel
      </button>
      <button
        type="button"
        onClick={onProceed}
        className="px-2 py-0.5 rounded text-[11.5px] font-mono bg-ao-accent text-white hover:opacity-90 focus:outline-none focus-visible:ring-2 focus-visible:ring-ao-accent-line"
      >
        Regenerate
      </button>
    </div>
  );
}

function Spinner() {
  return (
    <span
      aria-hidden
      className="inline-block w-3 h-3 rounded-full border-2 border-ao-line-2 border-t-ao-accent animate-spin"
    />
  );
}

function ErrorPill() {
  return (
    <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-md bg-red-500/10 text-red-300 border border-red-500/20 text-[11.5px] font-mono">
      <Icon name="zap" size={11} /> Last regen failed
    </span>
  );
}
